(() => {
'use strict';
const CONFIG=window.URBAN_STAY_SUPABASE||null;
const DB=CONFIG&&window.supabase?.createClient?window.supabase.createClient(CONFIG.url,CONFIG.publishableKey):null;
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let currentAdmin=null,profiles=[],properties=[],view='properties';
function message(text,error=false){const el=$('#adminMessage');el.textContent=text;el.className='form-message '+(error?'error':'');}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__adminToast);window.__adminToast=setTimeout(()=>el.classList.remove('show'),1800);}
function statusLabel(status){return ({pending:'Pendiente',approved:'Aprobado',rejected:'Rechazado'})[status]||status||'Pendiente';}
function formatDate(value){if(!value)return '—';try{return new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}catch{return value;}}
async function getOwnProfile(userId){const {data,error}=await DB.from('profiles').select('id,full_name,role,account_status').eq('id',userId).single();if(error)throw error;return data;}
async function requireAdmin(session){if(!session?.user)return false;const profile=await getOwnProfile(session.user.id);if(profile.role!=='admin'||profile.account_status!=='approved'){await DB.auth.signOut();message('Esta cuenta no tiene permisos de administrador.',true);return false;}currentAdmin=profile;$('#adminLogin').hidden=true;$('#adminConsole').hidden=false;$('#adminLogout').hidden=false;await loadData();return true;}
async function login(){const email=$('#adminEmail').value.trim(),password=$('#adminPassword').value;if(!DB)return message('No se pudo conectar con el servidor.',true);if(!email||!password)return message('Escribe tu correo y contraseña.',true);message('Comprobando acceso…');const {data,error}=await DB.auth.signInWithPassword({email,password});if(error)return message('El correo o la contraseña no coinciden.',true);try{await requireAdmin(data.session);}catch(e){message('No se pudo comprobar el permiso de administrador.',true);}}
async function logout(){await DB.auth.signOut();currentAdmin=null;profiles=[];properties=[];$('#adminLogin').hidden=false;$('#adminConsole').hidden=true;$('#adminLogout').hidden=true;message('');}
async function loadData(){const [profilesResult,propertiesResult]=await Promise.all([DB.from('profiles').select('id,full_name,phone,company_name,role,account_status,created_at,reviewed_at,review_note').order('created_at',{ascending:false}),DB.from('properties').select('*').order('created_at',{ascending:false})]);if(profilesResult.error){$('#accountList').innerHTML='<article class="card"><h2>No se pudieron cargar las cuentas</h2><p>Comprueba la configuración de Supabase.</p></article>';return;}profiles=profilesResult.data||[];if(propertiesResult.error){properties=[];toast('No se pudieron cargar las propiedades');}else properties=propertiesResult.data||[];render();}
function getPropertyStatus(p){return p.review_status||'pending';}
function propertyOwnerId(p){return p.owner_id||p.user_id||p.profile_id||p.created_by||null;}
function propertyName(p){return p.name||p.title||p.property_name||p.accommodation_name||p.slug||'Propiedad sin nombre';}
function propertyLocation(p){return [p.address,p.city,p.country].filter(Boolean).join(' · ')||'Ubicación no indicada';}
function renderStats(items,statusGetter){const counts={pending:0,approved:0,rejected:0};items.forEach(item=>{const s=statusGetter(item);if(counts[s]!==undefined)counts[s]++;});$('#adminStats').innerHTML=`<article class="overview-card"><small>PENDIENTES</small><strong>${counts.pending}</strong></article><article class="overview-card"><small>APROBADOS</small><strong>${counts.approved}</strong></article><article class="overview-card"><small>RECHAZADOS</small><strong>${counts.rejected}</strong></article><article class="overview-card"><small>TOTAL</small><strong>${items.length}</strong></article>`;}
function renderAccounts(){renderStats(profiles,p=>p.account_status);$('#adminSectionLabel').textContent='SOLICITUDES DE ACCESO';$('#adminListTitle').textContent='Propietarios registrados';const filter=$('#accountFilter').value;const visible=profiles.filter(p=>filter==='all'||p.account_status===filter);$('#accountList').innerHTML=visible.length?visible.map(p=>`<article class="card admin-account"><div class="admin-account-head"><div><span class="status status--${esc(p.account_status)}">● ${statusLabel(p.account_status)}</span><h2>${esc(p.full_name||'Usuario sin nombre')}</h2><p>${esc(p.company_name||'Sin empresa')} · Alta ${formatDate(p.created_at)}</p></div><span class="admin-role">${p.role==='admin'?'Administrador':'Propietario'}</span></div>${p.review_note?`<div class="admin-note"><b>Nota de revisión</b><span>${esc(p.review_note)}</span></div>`:''}${p.id===currentAdmin?.id?'<p class="admin-self">Esta es tu cuenta de administrador.</p>':`<div class="admin-actions"><button class="btn secondary" data-account-review="rejected" data-id="${p.id}">Rechazar</button><button class="btn primary" data-account-review="approved" data-id="${p.id}">✓ Aprobar</button></div>`}</article>`).join(''):'<article class="card admin-empty"><h2>No hay propietarios en este estado</h2><p>Las nuevas solicitudes aparecerán aquí automáticamente.</p></article>';document.querySelectorAll('[data-account-review]').forEach(btn=>btn.addEventListener('click',()=>reviewAccount(btn.dataset.id,btn.dataset.accountReview)));}
function renderProperties(){renderStats(properties,getPropertyStatus);$('#adminSectionLabel').textContent='REVISIÓN DE PROPIEDADES';$('#adminListTitle').textContent='Alojamientos registrados';const filter=$('#accountFilter').value;const visible=properties.filter(p=>filter==='all'||getPropertyStatus(p)===filter);$('#accountList').innerHTML=visible.length?visible.map(p=>{const owner=profiles.find(x=>x.id===propertyOwnerId(p));const status=getPropertyStatus(p);return `<article class="card admin-account"><div class="admin-account-head"><div><span class="status status--${esc(status)}">● ${statusLabel(status)}</span><h2>${esc(propertyName(p))}</h2><p>${esc(propertyLocation(p))} · Alta ${formatDate(p.created_at)}</p></div><span class="admin-role">Propiedad</span></div><div class="admin-note"><b>Propietario</b><span>${esc(owner?.full_name||owner?.company_name||'Propietario registrado')}</span></div>${p.review_note?`<div class="admin-note"><b>Nota de revisión</b><span>${esc(p.review_note)}</span></div>`:''}<div class="admin-actions"><button class="btn secondary" data-property-review="rejected" data-id="${p.id}">Rechazar</button><button class="btn primary" data-property-review="approved" data-id="${p.id}">✓ Aprobar</button></div></article>`;}).join(''):'<article class="card admin-empty"><h2>No hay propiedades en este estado</h2><p>Las nuevas propiedades aparecerán aquí automáticamente para su revisión.</p></article>';document.querySelectorAll('[data-property-review]').forEach(btn=>btn.addEventListener('click',()=>reviewProperty(btn.dataset.id,btn.dataset.propertyReview)));}
function render(){document.querySelectorAll('[data-admin-view]').forEach(btn=>btn.classList.toggle('active',btn.dataset.adminView===view));if(view==='properties')renderProperties();else renderAccounts();}
async function reviewAccount(id,decision){const target=profiles.find(p=>p.id===id);if(!target)return;const verb=decision==='approved'?'aprobar':'rechazar';if(!confirm(`¿Quieres ${verb} la cuenta de ${target.full_name||'este usuario'}?`))return;const note=prompt('Nota interna opcional para esta decisión:','')||null;const {error}=await DB.rpc('review_account',{target_user_id:id,decision,note});if(error)return toast('No se pudo guardar la decisión');toast(decision==='approved'?'Cuenta aprobada':'Cuenta rechazada');await loadData();}
async function reviewProperty(id,decision){const target=properties.find(p=>String(p.id)===String(id));if(!target)return;const verb=decision==='approved'?'aprobar':'rechazar';if(!confirm(`¿Quieres ${verb} la propiedad ${propertyName(target)}?`))return;const note=prompt('Nota interna opcional para esta decisión:','')||null;const {error}=await DB.rpc('review_property',{target_property_id:id,decision,note});if(error){console.error(error);return toast('No se pudo guardar la decisión');}toast(decision==='approved'?'Propiedad aprobada':'Propiedad rechazada');await loadData();}
$('#adminLoginButton').addEventListener('click',login);$('#adminPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login();});$('#adminLogout').addEventListener('click',logout);$('#accountFilter').addEventListener('change',render);document.querySelectorAll('[data-admin-view]').forEach(btn=>btn.addEventListener('click',()=>{view=btn.dataset.adminView;$('#accountFilter').value='pending';render();}));
(async()=>{if(!DB)return message('Falta la configuración de Supabase.',true);const {data}=await DB.auth.getSession();if(data.session){try{await requireAdmin(data.session);}catch{message('No se pudo comprobar la sesión.',true);}}})();
})();