(() => {
'use strict';
const DB=window.URBAN_STAY_SUPABASE&&window.supabase?.createClient?window.supabase.createClient(window.URBAN_STAY_SUPABASE.url,window.URBAN_STAY_SUPABASE.publishableKey):null;
const ROOT_ID='discoverManagerRoot';
const SELECTED_KEY='usp-v1-selected-property';
const PROPS_KEY='usp-v1-properties';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const toast=msg=>{const e=document.querySelector('#toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(window.__discoverToast);window.__discoverToast=setTimeout(()=>e.classList.remove('show'),2200)};
let properties=[],selected=null,data={};
const defaults=()=>({restaurants:'',services:'',places:'',beaches:'',shopping:'',tips:''});
function hideHost(){const h=document.querySelector('#appContent');if(h){h.style.visibility='hidden';h.style.minHeight='70vh'}}
function showHost(){const h=document.querySelector('#appContent');if(h){h.style.visibility='visible';h.style.minHeight=''}}
async function getProperties(){if(!DB)return[];const{data:auth}=await DB.auth.getUser();const uid=auth?.user?.id;if(!uid)return[];const{data:rows,error}=await DB.from('properties').select('id,name,city,country').eq('owner_id',uid).order('created_at',{ascending:false});if(error)throw error;return rows||[]}
async function loadDiscover(id){data=defaults();if(!DB||!id)return;const{data:row,error}=await DB.from('property_content').select('content,updated_at').eq('property_id',id).maybeSingle();if(error)throw error;const c=row?.content||{},d=c.discover||{};data={...data,restaurants:d.restaurants??c.restaurants??'',services:d.services??c.services??'',places:d.places??'',beaches:d.beaches??'',shopping:d.shopping??'',tips:d.tips??''};data.updatedAt=row?.updated_at||null}
function area(label,key,placeholder){return `<label class="discover-field"><b>${label}</b><textarea data-discover-field="${key}" placeholder="${placeholder}">${esc(data[key])}</textarea></label>`}
function listMarkup(text,empty){const rows=String(text||'').split('\n').map(x=>x.trim()).filter(Boolean);return rows.length?`<ul>${rows.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p class="discover-empty">${empty}</p>`}
function renderMarkup(){const p=properties.find(x=>x.id===selected)||properties[0];if(!p)return `<section class="page"><div class="page-title"><div><span class="section-label">DESCUBRIR</span><h1>Descubrir</h1><p>Añade primero una propiedad para crear recomendaciones.</p></div></div></section>`;return `<style>
#${ROOT_ID}{max-width:1320px;margin:0 auto}.discover-head{display:flex;justify-content:space-between;gap:28px;align-items:end;margin-bottom:26px}.discover-head h1{font-family:Georgia,serif;font-size:48px;color:#09243a;margin:6px 0}.discover-head p{font-size:19px;color:#6c8196;margin:0}.discover-property{min-width:300px}.discover-property b,.discover-field>b{display:block;margin-bottom:8px;color:#102b40}.discover-property select,.discover-field textarea{width:100%;box-sizing:border-box;border:1px solid #d6e0e8;border-radius:15px;background:#fff;padding:15px 17px;font:inherit;color:#102b40}.discover-field textarea{min-height:120px;resize:vertical}.discover-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.discover-card{background:#fff;border:1px solid #dbe4eb;border-radius:25px;padding:28px;box-shadow:0 10px 30px rgba(10,35,55,.04)}.discover-card h2{margin:0 0 20px;color:#09243a;font-size:25px}.discover-field{display:block;margin-bottom:18px}.discover-preview{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.discover-preview article{background:#f5f8fa;border-radius:18px;padding:20px}.discover-preview h3{margin:0 0 10px;color:#09243a}.discover-preview ul{margin:0;padding-left:20px;color:#526b80}.discover-preview li{margin:6px 0}.discover-empty{color:#8293a3;margin:0}.discover-actions{display:flex;justify-content:flex-end;gap:14px;align-items:center;margin-top:22px}.discover-save{border:0;border-radius:14px;padding:15px 24px;background:#062a43;color:#fff;font-weight:800;font-size:17px;cursor:pointer}.discover-updated{font-size:14px;color:#71869a}@media(max-width:900px){.discover-head{display:block}.discover-property{margin-top:20px;min-width:0}.discover-grid,.discover-preview{grid-template-columns:1fr}.discover-head h1{font-size:38px}}
</style><section id="${ROOT_ID}"><div class="discover-head"><div><span class="section-label">RECOMENDACIONES DEL DESTINO</span><h1>Descubrir</h1><p>Organiza los lugares y servicios que quieres recomendar a tus huéspedes en ${esc(p.city||'el destino')}.</p></div><label class="discover-property"><b>Propiedad</b><select id="discoverProperty">${properties.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label></div><div class="discover-grid"><div class="discover-card"><h2>Gastronomía y servicios</h2>${area('Restaurantes recomendados','restaurants','Un lugar por línea\nEj. El Nisio\nCasa Moncho')}${area('Servicios cercanos','services','Un servicio por línea\nEj. Supermercado\nFarmacia\nTaxi')}</div><div class="discover-card"><h2>Qué hacer</h2>${area('Lugares para visitar','places','Un lugar por línea\nEj. Casco Vello\nMonte do Castro')}${area('Playas','beaches','Una playa por línea')}${area('Compras y productos locales','shopping','Tiendas, mercados o productos recomendados')}${area('Consejos del anfitrión','tips','Indicaciones o recomendaciones generales para disfrutar la ciudad')}</div></div><div class="discover-card" style="margin-top:22px"><h2>Vista para el huésped</h2><div class="discover-preview" id="discoverPreview"></div><div class="discover-actions"><span class="discover-updated" id="discoverUpdated">${data.updatedAt?'Última actualización: '+new Date(data.updatedAt).toLocaleString('es-ES'):''}</span><button class="discover-save" id="saveDiscover">Guardar recomendaciones</button></div></div></section>`}
function updatePreview(){const e=document.querySelector('#discoverPreview');if(!e)return;e.innerHTML=`<article><h3>🍽 Restaurantes</h3>${listMarkup(data.restaurants,'Todavía sin restaurantes añadidos.')}</article><article><h3>📍 Lugares para visitar</h3>${listMarkup(data.places,'Todavía sin lugares añadidos.')}</article><article><h3>🏖 Playas</h3>${listMarkup(data.beaches,'Todavía sin playas añadidas.')}</article><article><h3>🛍 Compras y servicios</h3>${listMarkup([data.shopping,data.services].filter(Boolean).join('\n'),'Todavía sin recomendaciones añadidas.')}</article>${data.tips?`<article style="grid-column:1/-1"><h3>💡 Consejos del anfitrión</h3><p>${esc(data.tips).replace(/\n/g,'<br>')}</p></article>`:''}`}
function syncLocal(){try{const props=JSON.parse(localStorage.getItem(PROPS_KEY)||'[]'),idx=props.findIndex(p=>String(p.id)===String(selected));if(idx<0)return;const wd=props[idx].wizardData||{};props[idx]={...props[idx],updated:new Date().toLocaleDateString('es-ES'),wizardData:{...wd,restaurants:data.restaurants,services:data.services,discover:{restaurants:data.restaurants,services:data.services,places:data.places,beaches:data.beaches,shopping:data.shopping,tips:data.tips}}};localStorage.setItem(PROPS_KEY,JSON.stringify(props))}catch(e){console.warn('Urban Stay discover local sync failed',e)}}
async function save(){if(!DB||!selected)return toast('No se pudo conectar con Supabase');const{data:row,error:rerr}=await DB.from('property_content').select('content').eq('property_id',selected).maybeSingle();if(rerr)return toast('No se pudo guardar');const previous=row?.content||{};const content={...previous,restaurants:data.restaurants,services:data.services,discover:{restaurants:data.restaurants,services:data.services,places:data.places,beaches:data.beaches,shopping:data.shopping,tips:data.tips}};const{error}=await DB.from('property_content').upsert({property_id:selected,content},{onConflict:'property_id'});if(error){console.error(error);return toast('No se pudieron guardar las recomendaciones')}syncLocal();data.updatedAt=new Date().toISOString();const u=document.querySelector('#discoverUpdated');if(u)u.textContent='Actualizado ahora';toast('✓ Recomendaciones guardadas y sincronizadas')}
async function renderDiscover(){const host=document.querySelector('#appContent');if(!host)return;hideHost();try{properties=await getProperties();const stored=localStorage.getItem(SELECTED_KEY);selected=properties.some(p=>p.id===stored)?stored:properties[0]?.id||null;if(selected)localStorage.setItem(SELECTED_KEY,selected);await loadDiscover(selected);host.innerHTML=renderMarkup();updatePreview();bind()}catch(err){console.error(err);toast('No se pudo cargar Descubrir')}finally{showHost()}}
function bind(){const root=document.querySelector('#'+ROOT_ID);if(!root)return;root.addEventListener('input',e=>{const k=e.target.dataset.discoverField;if(!k)return;data[k]=e.target.value;updatePreview()});root.addEventListener('change',async e=>{if(e.target.id==='discoverProperty'){hideHost();selected=e.target.value;localStorage.setItem(SELECTED_KEY,selected);await loadDiscover(selected);document.querySelector('#appContent').innerHTML=renderMarkup();updatePreview();bind();showHost()}});document.querySelector('#saveDiscover')?.addEventListener('click',save)}
document.addEventListener('click',e=>{if(e.target.closest('[data-route="discover"]')){hideHost();setTimeout(renderDiscover,70)}},true);if(document.readyState!=='loading'&&document.querySelector('[data-route="discover"].active')){hideHost();setTimeout(renderDiscover,70)}
})();