(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const KEY='usp-v1-properties';
const SELECTED='usp-guide-selected-property';
const GUIDE_KEY=id=>`usp-guide-${id}`;
function readJson(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}}
function writeJson(k,v){localStorage.setItem(k,JSON.stringify(v))}
function props(){return readJson(KEY,[]).filter(p=>!p.isDemo)}
function activeProps(){return props().filter(p=>['active','approved','inactive'].includes(p.status))}
function guideData(id){return readJson(GUIDE_KEY(id),{welcome:'',houseRules:'',checkin:'',checkout:'',contact:'',notes:'',published:false,updatedAt:null})}
function saveGuide(id,data){writeJson(GUIDE_KEY(id),data)}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function propName(p){return p?.name||p?.wizardData?.name||'Propiedad'}
function propCity(p){return p?.city||p?.wizardData?.city||''}
function propCover(p){const wd=p?.wizardData||{};return wd.photos?.[wd.coverIndex||0]||wd.photos?.[0]||''}
function current(){const list=activeProps();let id=localStorage.getItem(SELECTED);let p=list.find(x=>String(x.id)===String(id));if(!p&&list[0]){p=list[0];localStorage.setItem(SELECTED,p.id)}return p||null}
function style(){if($('#uspGuideBuilderStyle'))return;const s=document.createElement('style');s.id='uspGuideBuilderStyle';s.textContent=`
#appContent,.usp-guide,.usp-guide *{pointer-events:auto!important}.usp-guide{position:relative;z-index:5;display:grid;gap:18px}.usp-guide input,.usp-guide textarea,.usp-guide select,.usp-guide button{position:relative;z-index:20!important;pointer-events:auto!important}.usp-guide-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.usp-guide-head h1{margin:5px 0 6px;font:600 38px Georgia,serif}.usp-guide-head p{margin:0;color:#6b7b88}.usp-guide-select{display:grid;gap:6px;min-width:260px}.usp-guide-select label{font-size:11px;font-weight:800;color:#7b6b45}.usp-guide-select select{padding:12px 14px;border:1px solid #dbe3e8;border-radius:12px;background:#fff;font:inherit}.usp-guide-grid{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(320px,.9fr);gap:18px}.usp-guide-editor,.usp-guide-preview{padding:22px}.usp-guide-editor h2,.usp-guide-preview h2{margin:0 0 14px}.usp-guide-fields{display:grid;gap:14px}.usp-guide-fields label{display:grid;gap:7px;font-size:12px;font-weight:800}.usp-guide-fields input,.usp-guide-fields textarea{width:100%;box-sizing:border-box;border:1px solid #dbe3e8;border-radius:12px;padding:12px 14px;font:inherit;background:#fff;color:#102638}.usp-guide-fields textarea{min-height:92px;resize:vertical}.usp-guide-actions{display:flex;gap:10px;justify-content:flex-end;margin-top:16px}.usp-guide-preview-card{overflow:hidden;border:1px solid #e1e7eb;border-radius:18px;background:#fff}.usp-guide-cover{min-height:180px;background:linear-gradient(135deg,#0a2e45,#164f6f);background-size:cover;background-position:center;display:flex;align-items:flex-end;padding:22px;color:#fff}.usp-guide-cover h3{margin:0;font:600 34px Georgia,serif}.usp-guide-cover span{display:block;font-size:12px;margin-bottom:6px;letter-spacing:.08em}.usp-guide-preview-body{padding:18px;display:grid;gap:12px}.usp-guide-preview-body article{padding:14px;border-radius:12px;background:#f7f9fb}.usp-guide-preview-body b{display:block;margin-bottom:5px}.usp-guide-status{display:inline-flex;gap:6px;align-items:center;padding:7px 10px;border-radius:999px;font-size:11px;font-weight:800;background:#eef3f7}.usp-guide-status.published{background:#eef8f1;color:#1c7b4b}.usp-guide-empty{padding:38px;text-align:center}.usp-guide-empty h2{margin:0 0 8px}.usp-guide-empty p{color:#6b7b88}.usp-guide-toolbar{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:14px}.usp-guide-published-note{font-size:11px;color:#6b7b88}.usp-guide-flash{margin-top:12px;padding:10px 12px;border-radius:10px;background:#eef8f1;color:#1c7b4b;font-size:12px;font-weight:800}@media(max-width:900px){.usp-guide-grid{grid-template-columns:1fr}.usp-guide-head{flex-direction:column}.usp-guide-select{width:100%}}
`;document.head.appendChild(s)}
function renderPreview(p,g){const cover=propCover(p);return `<div class="usp-guide-preview-card"><div class="usp-guide-cover" ${cover?`style="background-image:linear-gradient(rgba(0,0,0,.25),rgba(0,0,0,.45)),url('${cover}')"`:''}><div><span>URBAN STAY GUIDE</span><h3>${esc(propName(p))}</h3><small>${esc(propCity(p))}</small></div></div><div class="usp-guide-preview-body"><article><b>Bienvenida</b><span>${esc(g.welcome||'Añade un mensaje de bienvenida para tus huéspedes.')}</span></article><article><b>Check-in / Check-out</b><span>${esc([g.checkin&&`Entrada: ${g.checkin}`,g.checkout&&`Salida: ${g.checkout}`].filter(Boolean).join(' · ')||'Todavía sin horarios.')}</span></article><article><b>Normas de la casa</b><span>${esc(g.houseRules||'Todavía sin normas añadidas.')}</span></article><article><b>Información adicional</b><span>${esc(g.notes||'Puedes añadir recomendaciones o indicaciones útiles.')}</span></article></div></div>`}
function renderGuide(){const c=$('#appContent');if(!c)return;style();const list=activeProps();if(!list.length){c.innerHTML=`<section class="page usp-guide"><div class="usp-guide-empty card"><h2>No hay propiedades disponibles para crear una guía</h2><p>Primero necesitas una propiedad aprobada por Urban Stay.</p></div></section>`;return}const p=current();const g=guideData(p.id);c.innerHTML=`<section class="page usp-guide"><div class="usp-guide-head"><div><span class="section-label">CONSTRUCTOR DE GUÍA</span><h1>Guía del alojamiento</h1><p>Cada propiedad tiene su propia guía independiente para huéspedes.</p></div><div class="usp-guide-select"><label>Propiedad</label><select id="uspGuideProperty">${list.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(p.id)?'selected':''}>${esc(propName(x))}</option>`).join('')}</select></div></div><div class="usp-guide-grid"><article class="card usp-guide-editor"><div class="usp-guide-toolbar"><div><h2>Contenido de la guía</h2><span class="usp-guide-status ${g.published?'published':''}">${g.published?'● Publicada':'● Borrador'}</span></div><span class="usp-guide-published-note">${g.updatedAt?'Actualizada '+new Date(g.updatedAt).toLocaleString('es-ES'):''}</span></div><div class="usp-guide-fields"><label>Mensaje de bienvenida<textarea id="uspWelcome" placeholder="Ej. Bienvenidos a El almendro. Esperamos que disfrutéis vuestra estancia.">${esc(g.welcome||'')}</textarea></label><label>Check-in<input id="uspCheckin" value="${esc(g.checkin||'')}" placeholder="Ej. 16:00"></label><label>Check-out<input id="uspCheckout" value="${esc(g.checkout||'')}" placeholder="Ej. 12:00"></label><label>Normas de la casa<textarea id="uspRules" placeholder="Ruido, mascotas, fumar, etc.">${esc(g.houseRules||'')}</textarea></label><label>Contacto o asistencia<input id="uspContact" value="${esc(g.contact||'')}" placeholder="Opcional"></label><label>Información adicional<textarea id="uspNotes" placeholder="Recomendaciones, instrucciones, observaciones...">${esc(g.notes||'')}</textarea></label></div><div id="uspGuideFlash"></div><div class="usp-guide-actions"><button type="button" class="btn secondary" id="uspGuideSave">Guardar borrador</button><button type="button" class="btn primary" id="uspGuidePublish">${g.published?'Actualizar guía':'Publicar guía'}</button></div></article><article class="card usp-guide-preview"><h2>Vista del huésped</h2><div id="uspGuidePreview">${renderPreview(p,g)}</div></article></div></section>`;bindGuide(p)}
function collect(g){return {...g,welcome:$('#uspWelcome')?.value.trim()||'',checkin:$('#uspCheckin')?.value.trim()||'',checkout:$('#uspCheckout')?.value.trim()||'',houseRules:$('#uspRules')?.value.trim()||'',contact:$('#uspContact')?.value.trim()||'',notes:$('#uspNotes')?.value.trim()||'',updatedAt:new Date().toISOString()}}
function flash(text){const el=$('#uspGuideFlash');if(!el)return;el.className='usp-guide-flash';el.textContent=text;setTimeout(()=>{const cur=$('#uspGuideFlash');if(cur){cur.className='';cur.textContent=''}},1800)}
function persist(published){const p=current();if(!p)return;const g=collect(guideData(p.id));saveGuide(p.id,{...g,published});flash(published?'Guía publicada':'Borrador guardado correctamente');if(published)setTimeout(renderGuide,250)}
function bindGuide(){
 $('#uspGuideProperty')?.addEventListener('change',e=>{localStorage.setItem(SELECTED,e.target.value);renderGuide()});
 const refresh=()=>{const p=current(),holder=$('#uspGuidePreview');if(!p||!holder)return;holder.innerHTML=renderPreview(p,collect(guideData(p.id)))};
 $$('#uspWelcome,#uspCheckin,#uspCheckout,#uspRules,#uspContact,#uspNotes').forEach(el=>el.addEventListener('input',refresh));
}
window.addEventListener('click',e=>{
 const save=e.target.closest?.('#uspGuideSave');
 const publish=e.target.closest?.('#uspGuidePublish');
 if(!save&&!publish)return;
 e.preventDefault();
 e.stopImmediatePropagation();
 persist(!!publish);
},true);
function shouldRender(){return $('[data-route="guide"]')?.classList.contains('active')}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-route="guide"]'))setTimeout(renderGuide,120)});
document.addEventListener('DOMContentLoaded',()=>{if(shouldRender())setTimeout(renderGuide,120)});
})();