-- Urban Stay Platform · Backend y Seguridad · Fase 1
-- Migración inicial: usuarios, propiedades, contenido, eventos, auditoría y RLS.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  company_name text,
  role text not null default 'owner' check (role in ('owner','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.properties (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  slug text unique,
  city text not null,
  country text,
  address text,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.property_content (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null unique references public.properties(id) on delete cascade,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  source text not null default 'ticketmaster',
  external_id text,
  title text not null,
  description text,
  category text,
  venue text,
  city text,
  starts_at timestamptz not null,
  ends_at timestamptz,
  source_url text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(property_id, source, external_id)
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  action text not null,
  table_name text not null,
  record_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_properties_owner_id on public.properties(owner_id);
create index if not exists idx_properties_city on public.properties(city);
create index if not exists idx_events_property_id on public.events(property_id);
create index if not exists idx_events_starts_at on public.events(starts_at);
create index if not exists idx_audit_actor_id on public.audit_log(actor_id);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger properties_set_updated_at
before update on public.properties
for each row execute function public.set_updated_at();

create trigger property_content_set_updated_at
before update on public.property_content
for each row execute function public.set_updated_at();

create trigger events_set_updated_at
before update on public.events
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.log_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  rid text;
  meta jsonb;
begin
  rid := coalesce((to_jsonb(new)->>'id'), (to_jsonb(old)->>'id'));
  meta := jsonb_build_object('operation', tg_op);
  insert into public.audit_log(actor_id, action, table_name, record_id, metadata)
  values (auth.uid(), lower(tg_op), tg_table_name, rid, meta);
  return coalesce(new, old);
end;
$$;

create trigger audit_properties
after insert or update or delete on public.properties
for each row execute function public.log_change();

create trigger audit_property_content
after insert or update or delete on public.property_content
for each row execute function public.log_change();

create trigger audit_events
after insert or update or delete on public.events
for each row execute function public.log_change();

alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.property_content enable row level security;
alter table public.events enable row level security;
alter table public.audit_log enable row level security;

-- Perfiles: cada usuario solo ve y edita su propio perfil.
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (id = auth.uid());

create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Propiedades: cada propietario solo puede operar sobre las suyas.
create policy "properties_select_own"
on public.properties for select
to authenticated
using (owner_id = auth.uid());

create policy "properties_insert_own"
on public.properties for insert
to authenticated
with check (owner_id = auth.uid());

create policy "properties_update_own"
on public.properties for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

create policy "properties_delete_own"
on public.properties for delete
to authenticated
using (owner_id = auth.uid());

-- Contenido de guía: acceso únicamente si la propiedad pertenece al usuario.
create policy "property_content_select_own"
on public.property_content for select
to authenticated
using (exists (
  select 1 from public.properties p
  where p.id = property_content.property_id
    and p.owner_id = auth.uid()
));

create policy "property_content_insert_own"
on public.property_content for insert
to authenticated
with check (exists (
  select 1 from public.properties p
  where p.id = property_content.property_id
    and p.owner_id = auth.uid()
));

create policy "property_content_update_own"
on public.property_content for update
to authenticated
using (exists (
  select 1 from public.properties p
  where p.id = property_content.property_id
    and p.owner_id = auth.uid()
))
with check (exists (
  select 1 from public.properties p
  where p.id = property_content.property_id
    and p.owner_id = auth.uid()
));

create policy "property_content_delete_own"
on public.property_content for delete
to authenticated
using (exists (
  select 1 from public.properties p
  where p.id = property_content.property_id
    and p.owner_id = auth.uid()
));

-- Eventos: el propietario solo ve/gestiona eventos de sus propiedades.
create policy "events_select_own"
on public.events for select
to authenticated
using (exists (
  select 1 from public.properties p
  where p.id = events.property_id
    and p.owner_id = auth.uid()
));

create policy "events_insert_own"
on public.events for insert
to authenticated
with check (exists (
  select 1 from public.properties p
  where p.id = events.property_id
    and p.owner_id = auth.uid()
));

create policy "events_update_own"
on public.events for update
to authenticated
using (exists (
  select 1 from public.properties p
  where p.id = events.property_id
    and p.owner_id = auth.uid()
))
with check (exists (
  select 1 from public.properties p
  where p.id = events.property_id
    and p.owner_id = auth.uid()
));

create policy "events_delete_own"
on public.events for delete
to authenticated
using (exists (
  select 1 from public.properties p
  where p.id = events.property_id
    and p.owner_id = auth.uid()
));

-- Auditoría: un usuario autenticado solo puede leer su propio historial.
-- Las escrituras se realizan mediante trigger SECURITY DEFINER.
create policy "audit_select_own"
on public.audit_log for select
to authenticated
using (actor_id = auth.uid());

revoke all on public.audit_log from anon, authenticated;
grant select on public.audit_log to authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.properties to authenticated;
grant select, insert, update, delete on public.property_content to authenticated;
grant select, insert, update, delete on public.events to authenticated;

commit;
